
import os
import torch
import pandas as pd
import numpy as np
import tomllib
from pathlib import Path
from uqct.eval.run import setup_experiment
from uqct.ct import prepare_inputs_from_experiment, nll_mixture_angle_schedule
from uqct.datasets.utils import get_dataset

def verify_experiment_consistency(consolidated_file: Path):
    """
    Verifies that the experiments generated by setup_experiment match those
    used for the consolidated results by checking the NLL of FBP models.
    """
    print(f"Loading data from {consolidated_file}...")
    df = pd.read_parquet(consolidated_file)
    
    # Filter for FBP entries as they are deterministic given the experiment
    fbp_df = df[df["model"] == "fbp"]
    
    if fbp_df.empty:
        print("No FBP models found in consolidated file. Cannot verify determinism.")
        return

    # Select a sample: Sparse, Composite, Intensity 1e4 (sensitive to noise/counts)
    sample = fbp_df[
        (fbp_df["dataset"] == "composite") &
        (fbp_df["sparse"] == True) &
        (fbp_df["total_intensity"] == 1e4)
    ]
    
    if sample.empty:
        print("No matching sparse/composite/1e4 sample found. Picking first available FBP row.")
        sample = fbp_df
        
    row = sample.iloc[0]
    
    dataset = row["dataset"]
    total_intensity = row.get("total_intensity", row.get("intensity"))
    if total_intensity is None:
         # Print available columns to debug
         print(f"Available columns: {row.index.tolist()}")
         raise KeyError("Could not find 'total_intensity' or 'intensity' column.")

    sparse = row["sparse"]
    seed = row["seed"]
    image_idx = row.get("image_idx", 0) # This might be relative index in batch
    start_idx = row.get("image_start_index", 0)
    end_idx = row.get("image_end_index", 5) # Default chunk size
    
    # In consolidated parquet, 'nll_pred' is a LIST for one image.
    # But wait, consolidated parquet rows are "one row per image"?
    # Typically in plot_runs.py, consolidated file has one row per image-model combination?
    # Let's inspect the row structure.
    # If row["nll_pred"] is a list, then it corresponds to that single image.
    
    print(f"\nVerifying Sample:")
    print(f"Dataset: {dataset}, Intensity: {total_intensity}, Sparse: {sparse}, Seed: {seed}")
    print(f"Image Range: {start_idx} - {end_idx}")
    
    nll_pred_stored = np.array(row["nll_pred"])
    print(f"Stored NLL Pred Length: {len(nll_pred_stored)}")
    print(f"Stored NLL Sample (first 5): {nll_pred_stored[:5]}")
    
    # Re-simulate Experiment
    # We need schedule_length. Usually 32 for sparse. 
    # Load from settings or assume 32.
    schedule_length = 32
    
    print("Re-running setup_experiment...")
    gt, experiment, schedule = setup_experiment(
        dataset=dataset,
        image_range=(start_idx, end_idx),
        total_intensity=total_intensity,
        sparse=sparse,
        seed=seed,
        schedule_length=schedule_length
    )
    
    # Slicing to single image to save memory (and prevent 78GB alloc)
    # We must do this AFTER setup_experiment to preserve random state of counts
    local_idx = int(row.get("image_idx", start_idx) - start_idx)
    print(f"Slicing experiment to local index {local_idx} (Global {row.get('image_idx', '?')})")
    
    gt = gt[local_idx : local_idx + 1]
    experiment.counts = experiment.counts[local_idx : local_idx + 1]
    experiment.intensities = experiment.intensities[local_idx : local_idx + 1]

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    gt = gt.to(device)
    experiment.to(device)
    # Astra requires float32
    experiment.counts = experiment.counts.float()
    experiment.intensities = experiment.intensities.float()
    experiment.angles = experiment.angles.float()
    
    if schedule is not None:
        schedule = schedule.to(device)
        
    # Re-generate FBP predictions
    print("Generating FBP predictions...")
    preds, _, _ = prepare_inputs_from_experiment(experiment, schedule - 1 if schedule is not None else None)
    
    # Compute NLL
    print("Computing NLL locally...")
    print(f"Schedule Shape: {schedule.shape}")
    print(f"Preds Shape (Orig): {preds.shape}")
    
    # Squeeze batch dimension (N=1) and ADD P=1 dimension
    # Preds (Orig) seems to be (N, S, H, W) = (1, 32, 128, 128)
    # Target for nll_mixture (no batch): (S, P, H, W) = (32, 1, 128, 128)
    preds_sq = preds.squeeze(0).unsqueeze(1) 
    print(f"Preds Shape (Squeezed): {preds_sq.shape}")
    
    counts_sq = experiment.counts.squeeze(0)
    print(f"Counts Shape (Squeezed): {counts_sq.shape}")
    
    intensities_sq = experiment.intensities.squeeze(0)
    
    with torch.no_grad():
        nlls_computed = nll_mixture_angle_schedule(
            preds_sq, 
            counts_sq, 
            intensities_sq, 
            experiment.angles, 
            schedule,
            reduce=False # To get trajectory
        )
        
    # nlls_computed: (T,)
    nlls_computed_np = nlls_computed.cpu().numpy()
    
    # Since we squeezed, output is 1D array
    nll_computed = nlls_computed_np
    
    # Align lengths?
    L = min(len(nll_computed), len(nll_pred_stored))
    nll_c = nll_computed[-L:]
    nll_s = nll_pred_stored[-L:]
    
    print(f"\nComparison (Last {L} points):")
    print(f"Computed Sample: {nll_c[:5]}")
    print(f"Stored Sample:   {nll_s[:5]}")
    
    diff = np.abs(nll_c - nll_s)
    max_diff = diff.max()
    mean_diff = diff.mean()
    
    print(f"\nMax Diff: {max_diff:.6f}")
    print(f"Mean Diff: {mean_diff:.6f}")
    
    if max_diff < 1e-2:
        print("\nSUCCESS: Experiments are CONSISTENT.")
    else:
        print("\nFAILURE: Experiments represent DIFFERENT counts/seeds.")

if __name__ == "__main__":
    verify_experiment_consistency(Path("results/consolidated_all.parquet"))
