[eval-sparse]
seed_range = [0, 10]
datasets = ["lung", "composite", "lamino"]
image_range = [10, 110]
total_intensity_values = [1e4, 1e5, 1e6, 1e7, 1e8, 1e9]
models = ["fbp", "mle", "unet", "unet_ensemble", "diffusion"]
schedule_length = 32
num_angles = 200
max_angle = 180


[eval.mle]
lr = 1e-1
patience = 50
max_steps = 100
tv_weight = 0.0

[eval.map]
lr = 1e-1
patience = 50
max_steps = 100
tv_weight = -1.0

[eval.unet]
member = 0

[eval.diffusion]
gradient_steps = 20
guidance_lr = 1e-2
replicates = 16
cond = true

[eval-sparse.bootstrapping]
methods = ["fbp", "unet"]
n_bootstraps = 10
intensities = [1e6, 1e7, 1e8, 1e9]
seed_range = [0, 1]
