[eval-sparse]
seed_range = [0, 10]
datasets = ["lung", "composite", "lamino"]
image_range = [10, 170]
total_intensity_values = [1e4, 1e5, 1e6, 1e7, 1e8, 1e9]
models = ["fbp", "mle", "map", "unet", "diffusion"]
schedule_length = 32
num_angles = 200
max_angle = 180


[eval.mle]
lr = 1e-2
patience = 50
max_steps = 20000
tv_weight = -1.0

[eval.map]
lr = 1e-2
patience = 50
max_steps = 20000
tv_weight = -1.0

[eval.unet]
member = 0

[eval.diffusion]
gradient_steps = 20
guidance_lr = 1e-2
replicates = 16
cond = true
